language: node_js
node_js:
- '4.7'
- '6.9'
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: npm
  email: apiteam@swagger.io
  skip_cleanup: true
  api_key:
    secure: "junmsyqvifSfVfHfdQVl1vjXb2T6oqgP4V2MS4GR6Y6jAq053a/Pgr7O30uv0gIlsIVPxVAP4n+uYMHU9OlFJAqoRoExoK3ZBjFpBL5wmhLL1clOaLv7k98Gz/KqvdpO/8yxMh/XZXM944L2OPyMta4W8Tt9rBYHZ1DwwtK9eqs="
  on:
    tags: true
    repo: swagger-api/swagger-js
    node: '6.9'
